server:
  port: 8832

spring:
  application:
    name: service-feign
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  # 配置rabbitMq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  #引入其他配置文件，例如application-db.yml
  profiles:
    include: db

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

