eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8811/eureka/

server:
  port: 8832

spring:
  application:
    name: service-feign

  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhsot:8851

feign:
  hystrix:
    enabled: true

