eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8811/eureka/

server:
  port: 8821
spring:
  application:
    name: eureka-client
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true