spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/helloaija/cloud-parent
          searchPaths: /config-resp
          username:
          password:
    bus:
      trace:
        enabled: true
      enabled: true

server:
  port: 8851

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8811/eureka/

management:
  endpoint:
    web:
      exposure:
        include: bus-refresh