spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/helloaija/cloud-parent
          searchPaths: /config-resp
          username:
          password:
      label: master

server:
  port: 8851

