spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/helloaija/cloud-parent
          searchPaths: /config-resp
          username:
          password:

server:
  port: 8851

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8811/eureka/

